language: go
go:
- 1.8.1

before_install:
- go env
- go get -v
- go get -v github.com/golang/lint/golint

script:
- golint

before_deploy:
- go build .
- git config --local user.name "Naveen Kumar Sangi"
- git config --local user.email "naveenkumarsangi@protonmail.com"
- git tag "v$(cat VERSION).$(git log --format=%H -1)"

deploy:
  provider: releases
  api_key:
    secure: ATvDM19lgVfR4b3Og2vF1HOSTeERLnzwpwyxusKAZUa7QxqwvHj7lx7JUJV5GCJuA1YDMu5uYV3XYbsbFKO5nefgAzsAOxGYXJVMEkrXMWacb2S5kEAkFwse2XITPq8RJneEPXKsumz3GFuz82SBiuyTwbrCI8lW0i815drijqdbUJx3rbcRZM0vcue5IwEV+8O1I5YggK5EsNTjhMhCQCAJ73HThp8T36cQE1yTGkzoBoCUnYIWACDhbUKSEEzTVbHA3ygswqt5abvs6qXxSDGhWkLgnBRIv5GohIhMtmlo3p7wj4jPzn8zpWVd1BAHOl7fqegEUTSMQBp9TkIgc2wMxUYaCiJ7nsAujlCYAmfnlQ6/ZlMSjeCEdcV2LEMRPWCOyY8y1oiveA6J989CGAUyCrDHnpHcwBLgQxkB42sGIbez+Xa3lnBKWVsxxYf1v29BzjllAJzfdtnECHSersottDT9QsXptxdTSyD35ZA0252F8yUTvxKQdQc4uuUyvFC3VTYzSqwiY/W2n+Bp5q0j79xkrc2WIX487CigMmUow8c/s1tFh6LpSXtRfgzCIxNTeyab5Grtc4fi+TJX9AQC2D3220r+Ky4+VWi+DEaAFq4YR0xeMRT4Y3X0uf0VXPs/1c3whWBoI62l6qzDGdQ6ZIhxzb4FhsuCHpHdWFE=
  file: uipgo
  skip_cleanup: true
  on:
    repo: nkprince007/uipgo
    branch: master

notifications:
  email: false
